### ISSUE TITLE
1

### ISSUE THREAD

**Issue by dengqi105** [HungVu307/Few-shot-via-ensembling-Transformer-with-Mahalanobis-distance#1]
What should I call your proposed model?

**Comment by fantasy-zc** [comment]
> What should I call your proposed model?

Excuse me, do you know this model's name? There seem not a name if this model in paper.

**Comment by fantasy-zc** [comment]
> > What should I call your proposed model?
> 
> Excuse me, do you know this model's name? There seem be not a name if this model in paper.

hi, i probably know the model name, it seem be ETMD
