### ISSUE TITLE
Paderborn University dataset

### ISSUE THREAD

**Issue by HungVu307** [HungVu307/Few-shot-via-ensembling-Transformer-with-Mahalanobis-distance#3]
Hi guys, 

I receive many emails asking about PU dataset. Everyone can refer to the following link to download:
https://github.com/JvdHoogen/paderborn_bearing/blob/main/paderborn_bearing/datafiles.txt

Cheers, 
Hung

**Comment by yumingjie0405** [comment]
> 嗨，大家好，
> 
> 我收到很多邮件询问PU数据集，大家可以参考以下链接下载： https://github.com/JvdHoogen/paderborn_bearing/blob/main/paderborn_bearing/datafiles.txt
> 
> 干杯， 洪

Hello Author,
I would like to ask how you convert the original .mat format data and labels into .pt format data and labels? I have a custom dataset in a similar format to the PU dataset, and I would like to know the method of conversion.

**Comment by zhangVivian666** [comment]
> > 嗨，大家好，
> > 我收到很多邮件询问PU数据集，大家可以参考以下链接下载： https://github.com/JvdHoogen/paderborn_bearing/blob/main/paderborn_bearing/datafiles.txt
> > 干杯， 洪
> 
> Hello Author, I would like to ask how you convert the original .mat format data and labels into .pt format data and labels? I have a custom dataset in a similar format to the PU dataset, and I would like to know the method of conversion.
同学你好，我想问一下这一篇论文关于PU数据集预处理部分处理使相关事宜，方便交流一下吗？

**Comment by zhangVivian666** [comment]
> Hi guys,
> 
> I receive many emails asking about PU dataset. Everyone can refer to the following link to download: https://github.com/JvdHoogen/paderborn_bearing/blob/main/paderborn_bearing/datafiles.txt
> 
> Cheers, Hung

Hello Author,I encountered a little trouble when processing the PU dataset. The method structure I used was not satisfactory. The result of 1shot-trainsample195 was only about 60%, so I would like to ask if you are willing to provide [data.pt] and [label.pt]. If you can, I will be very grateful.
